// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_Eotq.proto3

#ifndef PROTOBUF_PB_5fEotq_2eproto3__INCLUDED
#define PROTOBUF_PB_5fEotq_2eproto3__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PB_Eotq {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PB_5fEotq_2eproto3();
void protobuf_AssignDesc_PB_5fEotq_2eproto3();
void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

class MsgResouces;

// ===================================================================

class MsgResouces : public ::google::protobuf::Message {
 public:
  MsgResouces();
  virtual ~MsgResouces();

  MsgResouces(const MsgResouces& from);

  inline MsgResouces& operator=(const MsgResouces& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgResouces& default_instance();

  void Swap(MsgResouces* other);

  // implements Message ----------------------------------------------

  inline MsgResouces* New() const { return New(NULL); }

  MsgResouces* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgResouces& from);
  void MergeFrom(const MsgResouces& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgResouces* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 lck = 1;
  void clear_lck();
  static const int kLckFieldNumber = 1;
  ::google::protobuf::uint32 lck() const;
  void set_lck(::google::protobuf::uint32 value);

  // optional uint32 rck = 2;
  void clear_rck();
  static const int kRckFieldNumber = 2;
  ::google::protobuf::uint32 rck() const;
  void set_rck(::google::protobuf::uint32 value);

  // optional uint32 val = 3;
  void clear_val();
  static const int kValFieldNumber = 3;
  ::google::protobuf::uint32 val() const;
  void set_val(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PB_Eotq.MsgResouces)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 lck_;
  ::google::protobuf::uint32 rck_;
  ::google::protobuf::uint32 val_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static MsgResouces* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgResouces

// optional uint32 lck = 1;
inline void MsgResouces::clear_lck() {
  lck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResouces::lck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResouces.lck)
  return lck_;
}
inline void MsgResouces::set_lck(::google::protobuf::uint32 value) {
  
  lck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResouces.lck)
}

// optional uint32 rck = 2;
inline void MsgResouces::clear_rck() {
  rck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResouces::rck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResouces.rck)
  return rck_;
}
inline void MsgResouces::set_rck(::google::protobuf::uint32 value) {
  
  rck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResouces.rck)
}

// optional uint32 val = 3;
inline void MsgResouces::clear_val() {
  val_ = 0u;
}
inline ::google::protobuf::uint32 MsgResouces::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResouces.val)
  return val_;
}
inline void MsgResouces::set_val(::google::protobuf::uint32 value) {
  
  val_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResouces.val)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace PB_Eotq

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PB_5fEotq_2eproto3__INCLUDED
