// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_Eotq.proto3

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PB_Eotq.proto3.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PB_Eotq {

namespace {

const ::google::protobuf::Descriptor* MsgResources_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgResources_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgResources_Slot_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgResources_Slot_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgResources_Token_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgResources_Token_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PB_5fEotq_2eproto3() {
  protobuf_AddDesc_PB_5fEotq_2eproto3();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PB_Eotq.proto3");
  GOOGLE_CHECK(file != NULL);
  MsgResources_descriptor_ = file->message_type(0);
  static const int MsgResources_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources, from_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources, val_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources, slot_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources, token_),
  };
  MsgResources_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgResources_descriptor_,
      MsgResources::default_instance_,
      MsgResources_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgResources),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources, _is_default_instance_));
  MsgResources_Slot_descriptor_ = MsgResources_descriptor_->nested_type(0);
  static const int MsgResources_Slot_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Slot, sck_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Slot, dck_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Slot, val_),
  };
  MsgResources_Slot_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgResources_Slot_descriptor_,
      MsgResources_Slot::default_instance_,
      MsgResources_Slot_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgResources_Slot),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Slot, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Slot, _is_default_instance_));
  MsgResources_Token_descriptor_ = MsgResources_descriptor_->nested_type(1);
  static const int MsgResources_Token_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Token, sck_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Token, dck_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Token, val_),
  };
  MsgResources_Token_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgResources_Token_descriptor_,
      MsgResources_Token::default_instance_,
      MsgResources_Token_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgResources_Token),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Token, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgResources_Token, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PB_5fEotq_2eproto3);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgResources_descriptor_, &MsgResources::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgResources_Slot_descriptor_, &MsgResources_Slot::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgResources_Token_descriptor_, &MsgResources_Token::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PB_5fEotq_2eproto3() {
  delete MsgResources::default_instance_;
  delete MsgResources_reflection_;
  delete MsgResources_Slot::default_instance_;
  delete MsgResources_Slot_reflection_;
  delete MsgResources_Token::default_instance_;
  delete MsgResources_Token_reflection_;
}

void protobuf_AddDesc_PB_5fEotq_2eproto3() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016PB_Eotq.proto3\022\007PB_Eotq\"\336\001\n\014MsgResourc"
    "es\022\014\n\004from\030\001 \001(\r\022\013\n\003val\030\002 \001(\014\022(\n\004slot\030\003 "
    "\001(\0132\032.PB_Eotq.MsgResources.Slot\022*\n\005token"
    "\030\004 \001(\0132\033.PB_Eotq.MsgResources.Token\032-\n\004S"
    "lot\022\013\n\003sck\030\001 \001(\r\022\013\n\003dck\030\002 \001(\r\022\013\n\003val\030\003 \001"
    "(\014\032.\n\005Token\022\013\n\003sck\030\001 \001(\r\022\013\n\003dck\030\002 \001(\r\022\013\n"
    "\003val\030\003 \001(\014b\006proto3", 258);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PB_Eotq.proto3", &protobuf_RegisterTypes);
  MsgResources::default_instance_ = new MsgResources();
  MsgResources_Slot::default_instance_ = new MsgResources_Slot();
  MsgResources_Token::default_instance_ = new MsgResources_Token();
  MsgResources::default_instance_->InitAsDefaultInstance();
  MsgResources_Slot::default_instance_->InitAsDefaultInstance();
  MsgResources_Token::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PB_5fEotq_2eproto3);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PB_5fEotq_2eproto3 {
  StaticDescriptorInitializer_PB_5fEotq_2eproto3() {
    protobuf_AddDesc_PB_5fEotq_2eproto3();
  }
} static_descriptor_initializer_PB_5fEotq_2eproto3_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int MsgResources_Slot::kSckFieldNumber;
const int MsgResources_Slot::kDckFieldNumber;
const int MsgResources_Slot::kValFieldNumber;
#endif  // !_MSC_VER

MsgResources_Slot::MsgResources_Slot()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_Eotq.MsgResources.Slot)
}

void MsgResources_Slot::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgResources_Slot::MsgResources_Slot(const MsgResources_Slot& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_Eotq.MsgResources.Slot)
}

void MsgResources_Slot::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  sck_ = 0u;
  dck_ = 0u;
  val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MsgResources_Slot::~MsgResources_Slot() {
  // @@protoc_insertion_point(destructor:PB_Eotq.MsgResources.Slot)
  SharedDtor();
}

void MsgResources_Slot::SharedDtor() {
  val_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MsgResources_Slot::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgResources_Slot::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgResources_Slot_descriptor_;
}

const MsgResources_Slot& MsgResources_Slot::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PB_5fEotq_2eproto3();
  return *default_instance_;
}

MsgResources_Slot* MsgResources_Slot::default_instance_ = NULL;

MsgResources_Slot* MsgResources_Slot::New(::google::protobuf::Arena* arena) const {
  MsgResources_Slot* n = new MsgResources_Slot;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgResources_Slot::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MsgResources_Slot*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(sck_, dck_);
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool MsgResources_Slot::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_Eotq.MsgResources.Slot)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 sck = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sck_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_dck;
        break;
      }

      // optional uint32 dck = 2;
      case 2: {
        if (tag == 16) {
         parse_dck:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dck_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_val;
        break;
      }

      // optional bytes val = 3;
      case 3: {
        if (tag == 26) {
         parse_val:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_val()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_Eotq.MsgResources.Slot)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_Eotq.MsgResources.Slot)
  return false;
#undef DO_
}

void MsgResources_Slot::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_Eotq.MsgResources.Slot)
  // optional uint32 sck = 1;
  if (this->sck() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->sck(), output);
  }

  // optional uint32 dck = 2;
  if (this->dck() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dck(), output);
  }

  // optional bytes val = 3;
  if (this->val().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->val(), output);
  }

  // @@protoc_insertion_point(serialize_end:PB_Eotq.MsgResources.Slot)
}

::google::protobuf::uint8* MsgResources_Slot::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_Eotq.MsgResources.Slot)
  // optional uint32 sck = 1;
  if (this->sck() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->sck(), target);
  }

  // optional uint32 dck = 2;
  if (this->dck() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dck(), target);
  }

  // optional bytes val = 3;
  if (this->val().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->val(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_Eotq.MsgResources.Slot)
  return target;
}

int MsgResources_Slot::ByteSize() const {
  int total_size = 0;

  // optional uint32 sck = 1;
  if (this->sck() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sck());
  }

  // optional uint32 dck = 2;
  if (this->dck() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dck());
  }

  // optional bytes val = 3;
  if (this->val().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->val());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgResources_Slot::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgResources_Slot* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgResources_Slot>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgResources_Slot::MergeFrom(const MsgResources_Slot& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.sck() != 0) {
    set_sck(from.sck());
  }
  if (from.dck() != 0) {
    set_dck(from.dck());
  }
  if (from.val().size() > 0) {

    val_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_);
  }
}

void MsgResources_Slot::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgResources_Slot::CopyFrom(const MsgResources_Slot& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgResources_Slot::IsInitialized() const {

  return true;
}

void MsgResources_Slot::Swap(MsgResources_Slot* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgResources_Slot::InternalSwap(MsgResources_Slot* other) {
  std::swap(sck_, other->sck_);
  std::swap(dck_, other->dck_);
  val_.Swap(&other->val_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgResources_Slot::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgResources_Slot_descriptor_;
  metadata.reflection = MsgResources_Slot_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MsgResources_Token::kSckFieldNumber;
const int MsgResources_Token::kDckFieldNumber;
const int MsgResources_Token::kValFieldNumber;
#endif  // !_MSC_VER

MsgResources_Token::MsgResources_Token()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_Eotq.MsgResources.Token)
}

void MsgResources_Token::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgResources_Token::MsgResources_Token(const MsgResources_Token& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_Eotq.MsgResources.Token)
}

void MsgResources_Token::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  sck_ = 0u;
  dck_ = 0u;
  val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MsgResources_Token::~MsgResources_Token() {
  // @@protoc_insertion_point(destructor:PB_Eotq.MsgResources.Token)
  SharedDtor();
}

void MsgResources_Token::SharedDtor() {
  val_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MsgResources_Token::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgResources_Token::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgResources_Token_descriptor_;
}

const MsgResources_Token& MsgResources_Token::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PB_5fEotq_2eproto3();
  return *default_instance_;
}

MsgResources_Token* MsgResources_Token::default_instance_ = NULL;

MsgResources_Token* MsgResources_Token::New(::google::protobuf::Arena* arena) const {
  MsgResources_Token* n = new MsgResources_Token;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgResources_Token::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MsgResources_Token*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(sck_, dck_);
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool MsgResources_Token::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_Eotq.MsgResources.Token)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 sck = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sck_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_dck;
        break;
      }

      // optional uint32 dck = 2;
      case 2: {
        if (tag == 16) {
         parse_dck:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dck_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_val;
        break;
      }

      // optional bytes val = 3;
      case 3: {
        if (tag == 26) {
         parse_val:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_val()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_Eotq.MsgResources.Token)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_Eotq.MsgResources.Token)
  return false;
#undef DO_
}

void MsgResources_Token::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_Eotq.MsgResources.Token)
  // optional uint32 sck = 1;
  if (this->sck() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->sck(), output);
  }

  // optional uint32 dck = 2;
  if (this->dck() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dck(), output);
  }

  // optional bytes val = 3;
  if (this->val().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->val(), output);
  }

  // @@protoc_insertion_point(serialize_end:PB_Eotq.MsgResources.Token)
}

::google::protobuf::uint8* MsgResources_Token::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_Eotq.MsgResources.Token)
  // optional uint32 sck = 1;
  if (this->sck() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->sck(), target);
  }

  // optional uint32 dck = 2;
  if (this->dck() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dck(), target);
  }

  // optional bytes val = 3;
  if (this->val().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->val(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_Eotq.MsgResources.Token)
  return target;
}

int MsgResources_Token::ByteSize() const {
  int total_size = 0;

  // optional uint32 sck = 1;
  if (this->sck() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sck());
  }

  // optional uint32 dck = 2;
  if (this->dck() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dck());
  }

  // optional bytes val = 3;
  if (this->val().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->val());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgResources_Token::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgResources_Token* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgResources_Token>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgResources_Token::MergeFrom(const MsgResources_Token& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.sck() != 0) {
    set_sck(from.sck());
  }
  if (from.dck() != 0) {
    set_dck(from.dck());
  }
  if (from.val().size() > 0) {

    val_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_);
  }
}

void MsgResources_Token::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgResources_Token::CopyFrom(const MsgResources_Token& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgResources_Token::IsInitialized() const {

  return true;
}

void MsgResources_Token::Swap(MsgResources_Token* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgResources_Token::InternalSwap(MsgResources_Token* other) {
  std::swap(sck_, other->sck_);
  std::swap(dck_, other->dck_);
  val_.Swap(&other->val_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgResources_Token::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgResources_Token_descriptor_;
  metadata.reflection = MsgResources_Token_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MsgResources::kFromFieldNumber;
const int MsgResources::kValFieldNumber;
const int MsgResources::kSlotFieldNumber;
const int MsgResources::kTokenFieldNumber;
#endif  // !_MSC_VER

MsgResources::MsgResources()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_Eotq.MsgResources)
}

void MsgResources::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  slot_ = const_cast< ::PB_Eotq::MsgResources_Slot*>(&::PB_Eotq::MsgResources_Slot::default_instance());
  token_ = const_cast< ::PB_Eotq::MsgResources_Token*>(&::PB_Eotq::MsgResources_Token::default_instance());
}

MsgResources::MsgResources(const MsgResources& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_Eotq.MsgResources)
}

void MsgResources::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  from_ = 0u;
  val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slot_ = NULL;
  token_ = NULL;
}

MsgResources::~MsgResources() {
  // @@protoc_insertion_point(destructor:PB_Eotq.MsgResources)
  SharedDtor();
}

void MsgResources::SharedDtor() {
  val_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete slot_;
    delete token_;
  }
}

void MsgResources::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgResources::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgResources_descriptor_;
}

const MsgResources& MsgResources::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PB_5fEotq_2eproto3();
  return *default_instance_;
}

MsgResources* MsgResources::default_instance_ = NULL;

MsgResources* MsgResources::New(::google::protobuf::Arena* arena) const {
  MsgResources* n = new MsgResources;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgResources::Clear() {
  from_ = 0u;
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && slot_ != NULL) delete slot_;
  slot_ = NULL;
  if (GetArenaNoVirtual() == NULL && token_ != NULL) delete token_;
  token_ = NULL;
}

bool MsgResources::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_Eotq.MsgResources)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 from = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &from_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_val;
        break;
      }

      // optional bytes val = 2;
      case 2: {
        if (tag == 18) {
         parse_val:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_val()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_slot;
        break;
      }

      // optional .PB_Eotq.MsgResources.Slot slot = 3;
      case 3: {
        if (tag == 26) {
         parse_slot:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_slot()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_token;
        break;
      }

      // optional .PB_Eotq.MsgResources.Token token = 4;
      case 4: {
        if (tag == 34) {
         parse_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_token()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_Eotq.MsgResources)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_Eotq.MsgResources)
  return false;
#undef DO_
}

void MsgResources::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_Eotq.MsgResources)
  // optional uint32 from = 1;
  if (this->from() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->from(), output);
  }

  // optional bytes val = 2;
  if (this->val().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->val(), output);
  }

  // optional .PB_Eotq.MsgResources.Slot slot = 3;
  if (this->has_slot()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->slot_, output);
  }

  // optional .PB_Eotq.MsgResources.Token token = 4;
  if (this->has_token()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->token_, output);
  }

  // @@protoc_insertion_point(serialize_end:PB_Eotq.MsgResources)
}

::google::protobuf::uint8* MsgResources::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_Eotq.MsgResources)
  // optional uint32 from = 1;
  if (this->from() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->from(), target);
  }

  // optional bytes val = 2;
  if (this->val().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->val(), target);
  }

  // optional .PB_Eotq.MsgResources.Slot slot = 3;
  if (this->has_slot()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *this->slot_, target);
  }

  // optional .PB_Eotq.MsgResources.Token token = 4;
  if (this->has_token()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, *this->token_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_Eotq.MsgResources)
  return target;
}

int MsgResources::ByteSize() const {
  int total_size = 0;

  // optional uint32 from = 1;
  if (this->from() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->from());
  }

  // optional bytes val = 2;
  if (this->val().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->val());
  }

  // optional .PB_Eotq.MsgResources.Slot slot = 3;
  if (this->has_slot()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->slot_);
  }

  // optional .PB_Eotq.MsgResources.Token token = 4;
  if (this->has_token()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->token_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgResources::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgResources* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgResources>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgResources::MergeFrom(const MsgResources& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.from() != 0) {
    set_from(from.from());
  }
  if (from.val().size() > 0) {

    val_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_);
  }
  if (from.has_slot()) {
    mutable_slot()->::PB_Eotq::MsgResources_Slot::MergeFrom(from.slot());
  }
  if (from.has_token()) {
    mutable_token()->::PB_Eotq::MsgResources_Token::MergeFrom(from.token());
  }
}

void MsgResources::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgResources::CopyFrom(const MsgResources& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgResources::IsInitialized() const {

  return true;
}

void MsgResources::Swap(MsgResources* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgResources::InternalSwap(MsgResources* other) {
  std::swap(from_, other->from_);
  val_.Swap(&other->val_);
  std::swap(slot_, other->slot_);
  std::swap(token_, other->token_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgResources::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgResources_descriptor_;
  metadata.reflection = MsgResources_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgResources_Slot

// optional uint32 sck = 1;
void MsgResources_Slot::clear_sck() {
  sck_ = 0u;
}
 ::google::protobuf::uint32 MsgResources_Slot::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Slot.sck)
  return sck_;
}
 void MsgResources_Slot::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Slot.sck)
}

// optional uint32 dck = 2;
void MsgResources_Slot::clear_dck() {
  dck_ = 0u;
}
 ::google::protobuf::uint32 MsgResources_Slot::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Slot.dck)
  return dck_;
}
 void MsgResources_Slot::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Slot.dck)
}

// optional bytes val = 3;
void MsgResources_Slot::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgResources_Slot::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Slot.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgResources_Slot::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Slot.val)
}
 void MsgResources_Slot::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.Slot.val)
}
 void MsgResources_Slot::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.Slot.val)
}
 ::std::string* MsgResources_Slot::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.Slot.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgResources_Slot::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgResources_Slot::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.Slot.val)
}

// -------------------------------------------------------------------

// MsgResources_Token

// optional uint32 sck = 1;
void MsgResources_Token::clear_sck() {
  sck_ = 0u;
}
 ::google::protobuf::uint32 MsgResources_Token::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Token.sck)
  return sck_;
}
 void MsgResources_Token::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Token.sck)
}

// optional uint32 dck = 2;
void MsgResources_Token::clear_dck() {
  dck_ = 0u;
}
 ::google::protobuf::uint32 MsgResources_Token::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Token.dck)
  return dck_;
}
 void MsgResources_Token::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Token.dck)
}

// optional bytes val = 3;
void MsgResources_Token::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgResources_Token::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Token.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgResources_Token::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Token.val)
}
 void MsgResources_Token::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.Token.val)
}
 void MsgResources_Token::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.Token.val)
}
 ::std::string* MsgResources_Token::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.Token.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgResources_Token::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgResources_Token::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.Token.val)
}

// -------------------------------------------------------------------

// MsgResources

// optional uint32 from = 1;
void MsgResources::clear_from() {
  from_ = 0u;
}
 ::google::protobuf::uint32 MsgResources::from() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.from)
  return from_;
}
 void MsgResources::set_from(::google::protobuf::uint32 value) {
  
  from_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.from)
}

// optional bytes val = 2;
void MsgResources::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgResources::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgResources::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.val)
}
 void MsgResources::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.val)
}
 void MsgResources::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.val)
}
 ::std::string* MsgResources::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgResources::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgResources::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.val)
}

// optional .PB_Eotq.MsgResources.Slot slot = 3;
bool MsgResources::has_slot() const {
  return !_is_default_instance_ && slot_ != NULL;
}
void MsgResources::clear_slot() {
  if (GetArenaNoVirtual() == NULL && slot_ != NULL) delete slot_;
  slot_ = NULL;
}
const ::PB_Eotq::MsgResources_Slot& MsgResources::slot() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.slot)
  return slot_ != NULL ? *slot_ : *default_instance_->slot_;
}
::PB_Eotq::MsgResources_Slot* MsgResources::mutable_slot() {
  
  if (slot_ == NULL) {
    slot_ = new ::PB_Eotq::MsgResources_Slot;
  }
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.slot)
  return slot_;
}
::PB_Eotq::MsgResources_Slot* MsgResources::release_slot() {
  
  ::PB_Eotq::MsgResources_Slot* temp = slot_;
  slot_ = NULL;
  return temp;
}
void MsgResources::set_allocated_slot(::PB_Eotq::MsgResources_Slot* slot) {
  delete slot_;
  slot_ = slot;
  if (slot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.slot)
}

// optional .PB_Eotq.MsgResources.Token token = 4;
bool MsgResources::has_token() const {
  return !_is_default_instance_ && token_ != NULL;
}
void MsgResources::clear_token() {
  if (GetArenaNoVirtual() == NULL && token_ != NULL) delete token_;
  token_ = NULL;
}
const ::PB_Eotq::MsgResources_Token& MsgResources::token() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.token)
  return token_ != NULL ? *token_ : *default_instance_->token_;
}
::PB_Eotq::MsgResources_Token* MsgResources::mutable_token() {
  
  if (token_ == NULL) {
    token_ = new ::PB_Eotq::MsgResources_Token;
  }
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.token)
  return token_;
}
::PB_Eotq::MsgResources_Token* MsgResources::release_token() {
  
  ::PB_Eotq::MsgResources_Token* temp = token_;
  token_ = NULL;
  return temp;
}
void MsgResources::set_allocated_token(::PB_Eotq::MsgResources_Token* token) {
  delete token_;
  token_ = token;
  if (token) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.token)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace PB_Eotq

// @@protoc_insertion_point(global_scope)
