// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_Eotq.proto3

#ifndef PROTOBUF_PB_5fEotq_2eproto3__INCLUDED
#define PROTOBUF_PB_5fEotq_2eproto3__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PB_Eotq {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PB_5fEotq_2eproto3();
void protobuf_AssignDesc_PB_5fEotq_2eproto3();
void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

class MsgResources;
class MsgResources_Map;
class Node;
class Node_Map;

// ===================================================================

class MsgResources_Map : public ::google::protobuf::Message {
 public:
  MsgResources_Map();
  virtual ~MsgResources_Map();

  MsgResources_Map(const MsgResources_Map& from);

  inline MsgResources_Map& operator=(const MsgResources_Map& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgResources_Map& default_instance();

  void Swap(MsgResources_Map* other);

  // implements Message ----------------------------------------------

  inline MsgResources_Map* New() const { return New(NULL); }

  MsgResources_Map* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgResources_Map& from);
  void MergeFrom(const MsgResources_Map& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgResources_Map* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 sck = 1;
  void clear_sck();
  static const int kSckFieldNumber = 1;
  ::google::protobuf::uint32 sck() const;
  void set_sck(::google::protobuf::uint32 value);

  // optional uint32 dck = 2;
  void clear_dck();
  static const int kDckFieldNumber = 2;
  ::google::protobuf::uint32 dck() const;
  void set_dck(::google::protobuf::uint32 value);

  // optional bytes val = 3;
  void clear_val();
  static const int kValFieldNumber = 3;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  void set_val(const char* value);
  void set_val(const void* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // @@protoc_insertion_point(class_scope:PB_Eotq.MsgResources.Map)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 sck_;
  ::google::protobuf::uint32 dck_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static MsgResources_Map* default_instance_;
};
// -------------------------------------------------------------------

class MsgResources : public ::google::protobuf::Message {
 public:
  MsgResources();
  virtual ~MsgResources();

  MsgResources(const MsgResources& from);

  inline MsgResources& operator=(const MsgResources& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgResources& default_instance();

  void Swap(MsgResources* other);

  // implements Message ----------------------------------------------

  inline MsgResources* New() const { return New(NULL); }

  MsgResources* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgResources& from);
  void MergeFrom(const MsgResources& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgResources* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MsgResources_Map Map;

  // accessors -------------------------------------------------------

  // optional uint32 from = 1;
  void clear_from();
  static const int kFromFieldNumber = 1;
  ::google::protobuf::uint32 from() const;
  void set_from(::google::protobuf::uint32 value);

  // optional bytes val = 2;
  void clear_val();
  static const int kValFieldNumber = 2;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  void set_val(const char* value);
  void set_val(const void* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // optional uint64 sck = 3;
  void clear_sck();
  static const int kSckFieldNumber = 3;
  ::google::protobuf::uint64 sck() const;
  void set_sck(::google::protobuf::uint64 value);

  // optional uint64 dck = 4;
  void clear_dck();
  static const int kDckFieldNumber = 4;
  ::google::protobuf::uint64 dck() const;
  void set_dck(::google::protobuf::uint64 value);

  // optional .PB_Eotq.MsgResources.Map slot = 5;
  bool has_slot() const;
  void clear_slot();
  static const int kSlotFieldNumber = 5;
  const ::PB_Eotq::MsgResources_Map& slot() const;
  ::PB_Eotq::MsgResources_Map* mutable_slot();
  ::PB_Eotq::MsgResources_Map* release_slot();
  void set_allocated_slot(::PB_Eotq::MsgResources_Map* slot);

  // optional .PB_Eotq.MsgResources.Map token = 6;
  bool has_token() const;
  void clear_token();
  static const int kTokenFieldNumber = 6;
  const ::PB_Eotq::MsgResources_Map& token() const;
  ::PB_Eotq::MsgResources_Map* mutable_token();
  ::PB_Eotq::MsgResources_Map* release_token();
  void set_allocated_token(::PB_Eotq::MsgResources_Map* token);

  // @@protoc_insertion_point(class_scope:PB_Eotq.MsgResources)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  ::google::protobuf::uint64 sck_;
  ::google::protobuf::uint64 dck_;
  ::PB_Eotq::MsgResources_Map* slot_;
  ::PB_Eotq::MsgResources_Map* token_;
  ::google::protobuf::uint32 from_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static MsgResources* default_instance_;
};
// -------------------------------------------------------------------

class Node_Map : public ::google::protobuf::Message {
 public:
  Node_Map();
  virtual ~Node_Map();

  Node_Map(const Node_Map& from);

  inline Node_Map& operator=(const Node_Map& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node_Map& default_instance();

  void Swap(Node_Map* other);

  // implements Message ----------------------------------------------

  inline Node_Map* New() const { return New(NULL); }

  Node_Map* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node_Map& from);
  void MergeFrom(const Node_Map& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node_Map* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 sck = 2;
  void clear_sck();
  static const int kSckFieldNumber = 2;
  ::google::protobuf::uint32 sck() const;
  void set_sck(::google::protobuf::uint32 value);

  // optional uint32 dck = 3;
  void clear_dck();
  static const int kDckFieldNumber = 3;
  ::google::protobuf::uint32 dck() const;
  void set_dck(::google::protobuf::uint32 value);

  // optional bytes val = 4;
  void clear_val();
  static const int kValFieldNumber = 4;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  void set_val(const char* value);
  void set_val(const void* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // @@protoc_insertion_point(class_scope:PB_Eotq.Node.Map)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 sck_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  ::google::protobuf::uint32 dck_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static Node_Map* default_instance_;
};
// -------------------------------------------------------------------

class Node : public ::google::protobuf::Message {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  void Swap(Node* other);

  // implements Message ----------------------------------------------

  inline Node* New() const { return New(NULL); }

  Node* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Node_Map Map;

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 sck = 2;
  void clear_sck();
  static const int kSckFieldNumber = 2;
  ::google::protobuf::uint32 sck() const;
  void set_sck(::google::protobuf::uint32 value);

  // optional uint32 dck = 3;
  void clear_dck();
  static const int kDckFieldNumber = 3;
  ::google::protobuf::uint32 dck() const;
  void set_dck(::google::protobuf::uint32 value);

  // optional string ip_addr = 4;
  void clear_ip_addr();
  static const int kIpAddrFieldNumber = 4;
  const ::std::string& ip_addr() const;
  void set_ip_addr(const ::std::string& value);
  void set_ip_addr(const char* value);
  void set_ip_addr(const char* value, size_t size);
  ::std::string* mutable_ip_addr();
  ::std::string* release_ip_addr();
  void set_allocated_ip_addr(::std::string* ip_addr);

  // optional uint32 port = 5;
  void clear_port();
  static const int kPortFieldNumber = 5;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // repeated .PB_Eotq.Node.Map slots = 6;
  int slots_size() const;
  void clear_slots();
  static const int kSlotsFieldNumber = 6;
  const ::PB_Eotq::Node_Map& slots(int index) const;
  ::PB_Eotq::Node_Map* mutable_slots(int index);
  ::PB_Eotq::Node_Map* add_slots();
  ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >*
      mutable_slots();
  const ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >&
      slots() const;

  // repeated .PB_Eotq.Node.Map tokens = 7;
  int tokens_size() const;
  void clear_tokens();
  static const int kTokensFieldNumber = 7;
  const ::PB_Eotq::Node_Map& tokens(int index) const;
  ::PB_Eotq::Node_Map* mutable_tokens(int index);
  ::PB_Eotq::Node_Map* add_tokens();
  ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >*
      mutable_tokens();
  const ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >&
      tokens() const;

  // @@protoc_insertion_point(class_scope:PB_Eotq.Node)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 sck_;
  ::google::protobuf::internal::ArenaStringPtr ip_addr_;
  ::google::protobuf::uint32 dck_;
  ::google::protobuf::uint32 port_;
  ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map > slots_;
  ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map > tokens_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static Node* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgResources_Map

// optional uint32 sck = 1;
inline void MsgResources_Map::clear_sck() {
  sck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources_Map::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Map.sck)
  return sck_;
}
inline void MsgResources_Map::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Map.sck)
}

// optional uint32 dck = 2;
inline void MsgResources_Map::clear_dck() {
  dck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources_Map::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Map.dck)
  return dck_;
}
inline void MsgResources_Map::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Map.dck)
}

// optional bytes val = 3;
inline void MsgResources_Map::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgResources_Map::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Map.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources_Map::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Map.val)
}
inline void MsgResources_Map::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.Map.val)
}
inline void MsgResources_Map::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.Map.val)
}
inline ::std::string* MsgResources_Map::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.Map.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgResources_Map::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources_Map::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.Map.val)
}

// -------------------------------------------------------------------

// MsgResources

// optional uint32 from = 1;
inline void MsgResources::clear_from() {
  from_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources::from() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.from)
  return from_;
}
inline void MsgResources::set_from(::google::protobuf::uint32 value) {
  
  from_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.from)
}

// optional bytes val = 2;
inline void MsgResources::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgResources::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.val)
}
inline void MsgResources::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.val)
}
inline void MsgResources::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.val)
}
inline ::std::string* MsgResources::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgResources::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.val)
}

// optional uint64 sck = 3;
inline void MsgResources::clear_sck() {
  sck_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MsgResources::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.sck)
  return sck_;
}
inline void MsgResources::set_sck(::google::protobuf::uint64 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.sck)
}

// optional uint64 dck = 4;
inline void MsgResources::clear_dck() {
  dck_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MsgResources::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.dck)
  return dck_;
}
inline void MsgResources::set_dck(::google::protobuf::uint64 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.dck)
}

// optional .PB_Eotq.MsgResources.Map slot = 5;
inline bool MsgResources::has_slot() const {
  return !_is_default_instance_ && slot_ != NULL;
}
inline void MsgResources::clear_slot() {
  if (GetArenaNoVirtual() == NULL && slot_ != NULL) delete slot_;
  slot_ = NULL;
}
inline const ::PB_Eotq::MsgResources_Map& MsgResources::slot() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.slot)
  return slot_ != NULL ? *slot_ : *default_instance_->slot_;
}
inline ::PB_Eotq::MsgResources_Map* MsgResources::mutable_slot() {
  
  if (slot_ == NULL) {
    slot_ = new ::PB_Eotq::MsgResources_Map;
  }
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.slot)
  return slot_;
}
inline ::PB_Eotq::MsgResources_Map* MsgResources::release_slot() {
  
  ::PB_Eotq::MsgResources_Map* temp = slot_;
  slot_ = NULL;
  return temp;
}
inline void MsgResources::set_allocated_slot(::PB_Eotq::MsgResources_Map* slot) {
  delete slot_;
  slot_ = slot;
  if (slot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.slot)
}

// optional .PB_Eotq.MsgResources.Map token = 6;
inline bool MsgResources::has_token() const {
  return !_is_default_instance_ && token_ != NULL;
}
inline void MsgResources::clear_token() {
  if (GetArenaNoVirtual() == NULL && token_ != NULL) delete token_;
  token_ = NULL;
}
inline const ::PB_Eotq::MsgResources_Map& MsgResources::token() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.token)
  return token_ != NULL ? *token_ : *default_instance_->token_;
}
inline ::PB_Eotq::MsgResources_Map* MsgResources::mutable_token() {
  
  if (token_ == NULL) {
    token_ = new ::PB_Eotq::MsgResources_Map;
  }
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.token)
  return token_;
}
inline ::PB_Eotq::MsgResources_Map* MsgResources::release_token() {
  
  ::PB_Eotq::MsgResources_Map* temp = token_;
  token_ = NULL;
  return temp;
}
inline void MsgResources::set_allocated_token(::PB_Eotq::MsgResources_Map* token) {
  delete token_;
  token_ = token;
  if (token) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.token)
}

// -------------------------------------------------------------------

// Node_Map

// optional uint32 id = 1;
inline void Node_Map::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Node_Map::id() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.Map.id)
  return id_;
}
inline void Node_Map::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.Map.id)
}

// optional uint32 sck = 2;
inline void Node_Map::clear_sck() {
  sck_ = 0u;
}
inline ::google::protobuf::uint32 Node_Map::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.Map.sck)
  return sck_;
}
inline void Node_Map::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.Map.sck)
}

// optional uint32 dck = 3;
inline void Node_Map::clear_dck() {
  dck_ = 0u;
}
inline ::google::protobuf::uint32 Node_Map::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.Map.dck)
  return dck_;
}
inline void Node_Map::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.Map.dck)
}

// optional bytes val = 4;
inline void Node_Map::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Node_Map::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.Map.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node_Map::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.Map.val)
}
inline void Node_Map::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.Node.Map.val)
}
inline void Node_Map::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.Node.Map.val)
}
inline ::std::string* Node_Map::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.Node.Map.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Node_Map::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node_Map::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.Node.Map.val)
}

// -------------------------------------------------------------------

// Node

// optional uint32 id = 1;
inline void Node::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Node::id() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.id)
  return id_;
}
inline void Node::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.id)
}

// optional uint32 sck = 2;
inline void Node::clear_sck() {
  sck_ = 0u;
}
inline ::google::protobuf::uint32 Node::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.sck)
  return sck_;
}
inline void Node::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.sck)
}

// optional uint32 dck = 3;
inline void Node::clear_dck() {
  dck_ = 0u;
}
inline ::google::protobuf::uint32 Node::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.dck)
  return dck_;
}
inline void Node::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.dck)
}

// optional string ip_addr = 4;
inline void Node::clear_ip_addr() {
  ip_addr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Node::ip_addr() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.ip_addr)
  return ip_addr_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_ip_addr(const ::std::string& value) {
  
  ip_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.ip_addr)
}
inline void Node::set_ip_addr(const char* value) {
  
  ip_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.Node.ip_addr)
}
inline void Node::set_ip_addr(const char* value, size_t size) {
  
  ip_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.Node.ip_addr)
}
inline ::std::string* Node::mutable_ip_addr() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.Node.ip_addr)
  return ip_addr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Node::release_ip_addr() {
  
  return ip_addr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_allocated_ip_addr(::std::string* ip_addr) {
  if (ip_addr != NULL) {
    
  } else {
    
  }
  ip_addr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip_addr);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.Node.ip_addr)
}

// optional uint32 port = 5;
inline void Node::clear_port() {
  port_ = 0u;
}
inline ::google::protobuf::uint32 Node::port() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.port)
  return port_;
}
inline void Node::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.Node.port)
}

// repeated .PB_Eotq.Node.Map slots = 6;
inline int Node::slots_size() const {
  return slots_.size();
}
inline void Node::clear_slots() {
  slots_.Clear();
}
inline const ::PB_Eotq::Node_Map& Node::slots(int index) const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.slots)
  return slots_.Get(index);
}
inline ::PB_Eotq::Node_Map* Node::mutable_slots(int index) {
  // @@protoc_insertion_point(field_mutable:PB_Eotq.Node.slots)
  return slots_.Mutable(index);
}
inline ::PB_Eotq::Node_Map* Node::add_slots() {
  // @@protoc_insertion_point(field_add:PB_Eotq.Node.slots)
  return slots_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >*
Node::mutable_slots() {
  // @@protoc_insertion_point(field_mutable_list:PB_Eotq.Node.slots)
  return &slots_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >&
Node::slots() const {
  // @@protoc_insertion_point(field_list:PB_Eotq.Node.slots)
  return slots_;
}

// repeated .PB_Eotq.Node.Map tokens = 7;
inline int Node::tokens_size() const {
  return tokens_.size();
}
inline void Node::clear_tokens() {
  tokens_.Clear();
}
inline const ::PB_Eotq::Node_Map& Node::tokens(int index) const {
  // @@protoc_insertion_point(field_get:PB_Eotq.Node.tokens)
  return tokens_.Get(index);
}
inline ::PB_Eotq::Node_Map* Node::mutable_tokens(int index) {
  // @@protoc_insertion_point(field_mutable:PB_Eotq.Node.tokens)
  return tokens_.Mutable(index);
}
inline ::PB_Eotq::Node_Map* Node::add_tokens() {
  // @@protoc_insertion_point(field_add:PB_Eotq.Node.tokens)
  return tokens_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >*
Node::mutable_tokens() {
  // @@protoc_insertion_point(field_mutable_list:PB_Eotq.Node.tokens)
  return &tokens_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PB_Eotq::Node_Map >&
Node::tokens() const {
  // @@protoc_insertion_point(field_list:PB_Eotq.Node.tokens)
  return tokens_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PB_Eotq

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PB_5fEotq_2eproto3__INCLUDED
