// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_Eotq.proto3

#ifndef PROTOBUF_PB_5fEotq_2eproto3__INCLUDED
#define PROTOBUF_PB_5fEotq_2eproto3__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PB_Eotq {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PB_5fEotq_2eproto3();
void protobuf_AssignDesc_PB_5fEotq_2eproto3();
void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

class MsgResources;
class MsgResources_Slot;
class MsgResources_Token;

// ===================================================================

class MsgResources_Slot : public ::google::protobuf::Message {
 public:
  MsgResources_Slot();
  virtual ~MsgResources_Slot();

  MsgResources_Slot(const MsgResources_Slot& from);

  inline MsgResources_Slot& operator=(const MsgResources_Slot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgResources_Slot& default_instance();

  void Swap(MsgResources_Slot* other);

  // implements Message ----------------------------------------------

  inline MsgResources_Slot* New() const { return New(NULL); }

  MsgResources_Slot* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgResources_Slot& from);
  void MergeFrom(const MsgResources_Slot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgResources_Slot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 sck = 1;
  void clear_sck();
  static const int kSckFieldNumber = 1;
  ::google::protobuf::uint32 sck() const;
  void set_sck(::google::protobuf::uint32 value);

  // optional uint32 dck = 2;
  void clear_dck();
  static const int kDckFieldNumber = 2;
  ::google::protobuf::uint32 dck() const;
  void set_dck(::google::protobuf::uint32 value);

  // optional bytes val = 3;
  void clear_val();
  static const int kValFieldNumber = 3;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  void set_val(const char* value);
  void set_val(const void* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // @@protoc_insertion_point(class_scope:PB_Eotq.MsgResources.Slot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 sck_;
  ::google::protobuf::uint32 dck_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static MsgResources_Slot* default_instance_;
};
// -------------------------------------------------------------------

class MsgResources_Token : public ::google::protobuf::Message {
 public:
  MsgResources_Token();
  virtual ~MsgResources_Token();

  MsgResources_Token(const MsgResources_Token& from);

  inline MsgResources_Token& operator=(const MsgResources_Token& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgResources_Token& default_instance();

  void Swap(MsgResources_Token* other);

  // implements Message ----------------------------------------------

  inline MsgResources_Token* New() const { return New(NULL); }

  MsgResources_Token* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgResources_Token& from);
  void MergeFrom(const MsgResources_Token& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgResources_Token* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 sck = 1;
  void clear_sck();
  static const int kSckFieldNumber = 1;
  ::google::protobuf::uint32 sck() const;
  void set_sck(::google::protobuf::uint32 value);

  // optional uint32 dck = 2;
  void clear_dck();
  static const int kDckFieldNumber = 2;
  ::google::protobuf::uint32 dck() const;
  void set_dck(::google::protobuf::uint32 value);

  // optional bytes val = 3;
  void clear_val();
  static const int kValFieldNumber = 3;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  void set_val(const char* value);
  void set_val(const void* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // @@protoc_insertion_point(class_scope:PB_Eotq.MsgResources.Token)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 sck_;
  ::google::protobuf::uint32 dck_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static MsgResources_Token* default_instance_;
};
// -------------------------------------------------------------------

class MsgResources : public ::google::protobuf::Message {
 public:
  MsgResources();
  virtual ~MsgResources();

  MsgResources(const MsgResources& from);

  inline MsgResources& operator=(const MsgResources& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgResources& default_instance();

  void Swap(MsgResources* other);

  // implements Message ----------------------------------------------

  inline MsgResources* New() const { return New(NULL); }

  MsgResources* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgResources& from);
  void MergeFrom(const MsgResources& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgResources* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MsgResources_Slot Slot;
  typedef MsgResources_Token Token;

  // accessors -------------------------------------------------------

  // optional uint32 from = 1;
  void clear_from();
  static const int kFromFieldNumber = 1;
  ::google::protobuf::uint32 from() const;
  void set_from(::google::protobuf::uint32 value);

  // optional bytes val = 2;
  void clear_val();
  static const int kValFieldNumber = 2;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  void set_val(const char* value);
  void set_val(const void* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // optional .PB_Eotq.MsgResources.Slot slot = 3;
  bool has_slot() const;
  void clear_slot();
  static const int kSlotFieldNumber = 3;
  const ::PB_Eotq::MsgResources_Slot& slot() const;
  ::PB_Eotq::MsgResources_Slot* mutable_slot();
  ::PB_Eotq::MsgResources_Slot* release_slot();
  void set_allocated_slot(::PB_Eotq::MsgResources_Slot* slot);

  // optional .PB_Eotq.MsgResources.Token token = 4;
  bool has_token() const;
  void clear_token();
  static const int kTokenFieldNumber = 4;
  const ::PB_Eotq::MsgResources_Token& token() const;
  ::PB_Eotq::MsgResources_Token* mutable_token();
  ::PB_Eotq::MsgResources_Token* release_token();
  void set_allocated_token(::PB_Eotq::MsgResources_Token* token);

  // @@protoc_insertion_point(class_scope:PB_Eotq.MsgResources)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  ::PB_Eotq::MsgResources_Slot* slot_;
  ::PB_Eotq::MsgResources_Token* token_;
  ::google::protobuf::uint32 from_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PB_5fEotq_2eproto3();
  friend void protobuf_AssignDesc_PB_5fEotq_2eproto3();
  friend void protobuf_ShutdownFile_PB_5fEotq_2eproto3();

  void InitAsDefaultInstance();
  static MsgResources* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgResources_Slot

// optional uint32 sck = 1;
inline void MsgResources_Slot::clear_sck() {
  sck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources_Slot::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Slot.sck)
  return sck_;
}
inline void MsgResources_Slot::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Slot.sck)
}

// optional uint32 dck = 2;
inline void MsgResources_Slot::clear_dck() {
  dck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources_Slot::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Slot.dck)
  return dck_;
}
inline void MsgResources_Slot::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Slot.dck)
}

// optional bytes val = 3;
inline void MsgResources_Slot::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgResources_Slot::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Slot.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources_Slot::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Slot.val)
}
inline void MsgResources_Slot::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.Slot.val)
}
inline void MsgResources_Slot::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.Slot.val)
}
inline ::std::string* MsgResources_Slot::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.Slot.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgResources_Slot::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources_Slot::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.Slot.val)
}

// -------------------------------------------------------------------

// MsgResources_Token

// optional uint32 sck = 1;
inline void MsgResources_Token::clear_sck() {
  sck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources_Token::sck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Token.sck)
  return sck_;
}
inline void MsgResources_Token::set_sck(::google::protobuf::uint32 value) {
  
  sck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Token.sck)
}

// optional uint32 dck = 2;
inline void MsgResources_Token::clear_dck() {
  dck_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources_Token::dck() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Token.dck)
  return dck_;
}
inline void MsgResources_Token::set_dck(::google::protobuf::uint32 value) {
  
  dck_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Token.dck)
}

// optional bytes val = 3;
inline void MsgResources_Token::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgResources_Token::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.Token.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources_Token::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.Token.val)
}
inline void MsgResources_Token::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.Token.val)
}
inline void MsgResources_Token::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.Token.val)
}
inline ::std::string* MsgResources_Token::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.Token.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgResources_Token::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources_Token::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.Token.val)
}

// -------------------------------------------------------------------

// MsgResources

// optional uint32 from = 1;
inline void MsgResources::clear_from() {
  from_ = 0u;
}
inline ::google::protobuf::uint32 MsgResources::from() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.from)
  return from_;
}
inline void MsgResources::set_from(::google::protobuf::uint32 value) {
  
  from_ = value;
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.from)
}

// optional bytes val = 2;
inline void MsgResources::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgResources::val() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_Eotq.MsgResources.val)
}
inline void MsgResources::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_Eotq.MsgResources.val)
}
inline void MsgResources::set_val(const void* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_Eotq.MsgResources.val)
}
inline ::std::string* MsgResources::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgResources::release_val() {
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgResources::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.val)
}

// optional .PB_Eotq.MsgResources.Slot slot = 3;
inline bool MsgResources::has_slot() const {
  return !_is_default_instance_ && slot_ != NULL;
}
inline void MsgResources::clear_slot() {
  if (GetArenaNoVirtual() == NULL && slot_ != NULL) delete slot_;
  slot_ = NULL;
}
inline const ::PB_Eotq::MsgResources_Slot& MsgResources::slot() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.slot)
  return slot_ != NULL ? *slot_ : *default_instance_->slot_;
}
inline ::PB_Eotq::MsgResources_Slot* MsgResources::mutable_slot() {
  
  if (slot_ == NULL) {
    slot_ = new ::PB_Eotq::MsgResources_Slot;
  }
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.slot)
  return slot_;
}
inline ::PB_Eotq::MsgResources_Slot* MsgResources::release_slot() {
  
  ::PB_Eotq::MsgResources_Slot* temp = slot_;
  slot_ = NULL;
  return temp;
}
inline void MsgResources::set_allocated_slot(::PB_Eotq::MsgResources_Slot* slot) {
  delete slot_;
  slot_ = slot;
  if (slot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.slot)
}

// optional .PB_Eotq.MsgResources.Token token = 4;
inline bool MsgResources::has_token() const {
  return !_is_default_instance_ && token_ != NULL;
}
inline void MsgResources::clear_token() {
  if (GetArenaNoVirtual() == NULL && token_ != NULL) delete token_;
  token_ = NULL;
}
inline const ::PB_Eotq::MsgResources_Token& MsgResources::token() const {
  // @@protoc_insertion_point(field_get:PB_Eotq.MsgResources.token)
  return token_ != NULL ? *token_ : *default_instance_->token_;
}
inline ::PB_Eotq::MsgResources_Token* MsgResources::mutable_token() {
  
  if (token_ == NULL) {
    token_ = new ::PB_Eotq::MsgResources_Token;
  }
  // @@protoc_insertion_point(field_mutable:PB_Eotq.MsgResources.token)
  return token_;
}
inline ::PB_Eotq::MsgResources_Token* MsgResources::release_token() {
  
  ::PB_Eotq::MsgResources_Token* temp = token_;
  token_ = NULL;
  return temp;
}
inline void MsgResources::set_allocated_token(::PB_Eotq::MsgResources_Token* token) {
  delete token_;
  token_ = token;
  if (token) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PB_Eotq.MsgResources.token)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PB_Eotq

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PB_5fEotq_2eproto3__INCLUDED
